# Base image for the client
FROM node:18

# Set working directory for the client
WORKDIR /app/client

# Copy client files
COPY client/package*.json ./

# Install dependencies
RUN npm install

# Install env-cmd globally
RUN npm install -g env-cmd

# Copy the client application files
COPY client/ .

# Copy the environment file
COPY .env /app/client/.env

# Expose the client port
EXPOSE 3000

# Start the client with env-cmd
CMD ["env-cmd", "-f", ".env", "vite"]

